CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE user_role AS ENUM ('admin', 'employee');
CREATE TYPE article_status AS ENUM ('draft', 'published', 'hidden');
CREATE TYPE translation_status AS ENUM (
  'original',
  'auto_translated',
  'reviewed'
);
CREATE TYPE contact_status AS ENUM (
  'new',
  'in_progress',
  'replied',
  'archived',
  'spam'
);
CREATE TYPE locale_code AS ENUM ('vi', 'en', 'zh');

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE cms_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar(255) NOT NULL,
  email citext NOT NULL,
  phone varchar(50),
  password_hash varchar(255) NOT NULL,
  role user_role NOT NULL DEFAULT 'employee',
  is_active boolean NOT NULL DEFAULT true,
  must_change_password boolean NOT NULL DEFAULT true,
  failed_login_count integer NOT NULL DEFAULT 0,
  locked_until timestamptz,
  last_login_at timestamptz,
  password_changed_at timestamptz,
  created_by integer,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uq_cms_users_email UNIQUE (email),
  CONSTRAINT chk_cms_users_failed_login_count
    CHECK (failed_login_count >= 0),
  CONSTRAINT fk_cms_users_created_by
    FOREIGN KEY (created_by)
    REFERENCES cms_users (id)
    ON DELETE SET NULL
);

CREATE TABLE auth_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id integer NOT NULL,
  refresh_token_hash varchar(255) NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  ip_address inet,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uq_auth_sessions_refresh_token_hash
    UNIQUE (refresh_token_hash),
  CONSTRAINT fk_auth_sessions_user
    FOREIGN KEY (user_id)
    REFERENCES cms_users (id)
    ON DELETE CASCADE
);

CREATE TABLE password_reset_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id integer NOT NULL,
  token_hash varchar(255) NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uq_password_reset_tokens_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_password_reset_tokens_user
    FOREIGN KEY (user_id)
    REFERENCES cms_users (id)
    ON DELETE CASCADE
);

CREATE TABLE news_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer,
  slug varchar(255) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uq_news_categories_slug UNIQUE (slug),
  CONSTRAINT chk_news_categories_sort_order CHECK (sort_order >= 0),
  CONSTRAINT chk_news_categories_not_own_parent
    CHECK (parent_id IS NULL OR parent_id <> id),
  CONSTRAINT fk_news_categories_parent
    FOREIGN KEY (parent_id)
    REFERENCES news_categories (id)
    ON DELETE SET NULL
);

CREATE TABLE news_category_translations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id integer NOT NULL,
  locale locale_code NOT NULL,
  name varchar(255) NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uq_news_category_translations_category_locale
    UNIQUE (category_id, locale),
  CONSTRAINT fk_news_category_translations_category
    FOREIGN KEY (category_id)
    REFERENCES news_categories (id)
    ON DELETE CASCADE
);

CREATE TABLE media_files (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uploaded_by integer NOT NULL,
  file_url varchar(1000) NOT NULL,
  file_name varchar(255) NOT NULL,
  mime_type varchar(100) NOT NULL,
  size_bytes bigint NOT NULL,
  alt_text varchar(500),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT chk_media_files_size_bytes CHECK (size_bytes > 0),
  CONSTRAINT fk_media_files_uploaded_by
    FOREIGN KEY (uploaded_by)
    REFERENCES cms_users (id)
    ON DELETE RESTRICT
);

CREATE TABLE news_articles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id integer,
  thumbnail_id integer,
  status article_status NOT NULL DEFAULT 'draft',
  is_featured boolean NOT NULL DEFAULT false,
  view_count integer NOT NULL DEFAULT 0,
  created_by integer NOT NULL,
  updated_by integer,
  published_by integer,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz,

  CONSTRAINT chk_news_articles_view_count CHECK (view_count >= 0),
  CONSTRAINT chk_news_articles_published_metadata CHECK (
    status <> 'published'
    OR (published_at IS NOT NULL AND published_by IS NOT NULL)
  ),
  CONSTRAINT fk_news_articles_category
    FOREIGN KEY (category_id)
    REFERENCES news_categories (id)
    ON DELETE SET NULL,
  CONSTRAINT fk_news_articles_thumbnail
    FOREIGN KEY (thumbnail_id)
    REFERENCES media_files (id)
    ON DELETE SET NULL,
  CONSTRAINT fk_news_articles_created_by
    FOREIGN KEY (created_by)
    REFERENCES cms_users (id)
    ON DELETE RESTRICT,
  CONSTRAINT fk_news_articles_updated_by
    FOREIGN KEY (updated_by)
    REFERENCES cms_users (id)
    ON DELETE SET NULL,
  CONSTRAINT fk_news_articles_published_by
    FOREIGN KEY (published_by)
    REFERENCES cms_users (id)
    ON DELETE SET NULL
);

CREATE TABLE news_article_translations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id integer NOT NULL,
  locale locale_code NOT NULL,
  title varchar(500) NOT NULL,
  slug varchar(500) NOT NULL,
  summary text,
  content text NOT NULL,
  seo_title varchar(500),
  seo_description text,
  translation_status translation_status NOT NULL DEFAULT 'auto_translated',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uq_news_article_translations_article_locale
    UNIQUE (article_id, locale),
  CONSTRAINT uq_news_article_translations_locale_slug
    UNIQUE (locale, slug),
  CONSTRAINT fk_news_article_translations_article
    FOREIGN KEY (article_id)
    REFERENCES news_articles (id)
    ON DELETE CASCADE
);

CREATE TABLE contact_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  phone varchar(50),
  message text NOT NULL,
  status contact_status NOT NULL DEFAULT 'new',
  handled_by integer,
  handled_at timestamptz,
  internal_note text,
  ip_address inet,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamptz,

  CONSTRAINT fk_contact_messages_handled_by
    FOREIGN KEY (handled_by)
    REFERENCES cms_users (id)
    ON DELETE SET NULL
);

CREATE TABLE activity_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer,
  action varchar(100) NOT NULL,
  entity_type varchar(100) NOT NULL,
  entity_id integer,
  description text,
  ip_address inet,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_activity_logs_user
    FOREIGN KEY (user_id)
    REFERENCES cms_users (id)
    ON DELETE SET NULL
);

CREATE INDEX idx_cms_users_role_is_active
  ON cms_users (role, is_active);
CREATE INDEX idx_cms_users_created_by
  ON cms_users (created_by);

CREATE INDEX idx_auth_sessions_user_id
  ON auth_sessions (user_id);
CREATE INDEX idx_auth_sessions_expires_at
  ON auth_sessions (expires_at);
CREATE INDEX idx_auth_sessions_active_user
  ON auth_sessions (user_id, expires_at)
  WHERE revoked_at IS NULL;

CREATE INDEX idx_password_reset_tokens_user_id
  ON password_reset_tokens (user_id);
CREATE INDEX idx_password_reset_tokens_active
  ON password_reset_tokens (user_id, expires_at)
  WHERE used_at IS NULL;

CREATE INDEX idx_news_categories_active_sort
  ON news_categories (is_active, sort_order, id);
CREATE INDEX idx_news_categories_parent_id
  ON news_categories (parent_id);
CREATE INDEX idx_news_category_translations_locale
  ON news_category_translations (locale);

CREATE INDEX idx_media_files_uploaded_by
  ON media_files (uploaded_by);
CREATE INDEX idx_media_files_created_at
  ON media_files (created_at DESC);

CREATE INDEX idx_news_articles_category_id
  ON news_articles (category_id);
CREATE INDEX idx_news_articles_created_by
  ON news_articles (created_by);
CREATE INDEX idx_news_articles_updated_by
  ON news_articles (updated_by);
CREATE INDEX idx_news_articles_published_by
  ON news_articles (published_by);
CREATE INDEX idx_news_articles_thumbnail_id
  ON news_articles (thumbnail_id);
CREATE INDEX idx_news_articles_status_deleted
  ON news_articles (status, deleted_at);
CREATE INDEX idx_news_articles_published
  ON news_articles (published_at DESC, id DESC)
  WHERE status = 'published' AND deleted_at IS NULL;

CREATE INDEX idx_news_article_translations_locale
  ON news_article_translations (locale);

CREATE INDEX idx_contact_messages_status_created
  ON contact_messages (status, created_at DESC)
  WHERE deleted_at IS NULL;
CREATE INDEX idx_contact_messages_handled_by
  ON contact_messages (handled_by);

CREATE INDEX idx_activity_logs_user_created
  ON activity_logs (user_id, created_at DESC);
CREATE INDEX idx_activity_logs_entity
  ON activity_logs (entity_type, entity_id, created_at DESC);
CREATE INDEX idx_activity_logs_action_created
  ON activity_logs (action, created_at DESC);

CREATE TRIGGER trg_cms_users_updated_at
BEFORE UPDATE ON cms_users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_auth_sessions_updated_at
BEFORE UPDATE ON auth_sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_news_categories_updated_at
BEFORE UPDATE ON news_categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_news_category_translations_updated_at
BEFORE UPDATE ON news_category_translations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_news_articles_updated_at
BEFORE UPDATE ON news_articles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_news_article_translations_updated_at
BEFORE UPDATE ON news_article_translations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_contact_messages_updated_at
BEFORE UPDATE ON contact_messages
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
